name: Release
on:
  push:
    tags:
      - "*"
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - name: Extract release note
        run: |
          ruby \
            -e 'print("## rake-compiler "); \
                puts(ARGF.read.split(/^### /)[1].gsub(/ {.+?}/, ""))' \
            History.md > release-note.md
      - name: Upload to release
        run: |
          title=$(head -n1 release-note.md | sed -e 's/^## //')
          tail -n +2 release-note.md > release-note-without-version.md
          gh release create ${GITHUB_REF_NAME} \
            --discussion-category Announcements \
            --notes-file release-note-without-version.md \
            --title "${title}"
        env:
          GH_TOKEN: ${{ github.token }}

  rubygems:
    name: RubyGems
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
    environment: release
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - uses: rubygems/configure-rubygems-credentials@v1.0.0
      - name: Push gems
        run: |
          bundle exec rake release:rubygem_push
